-- These queries run on the local outputs/retail.sqlite generated by analysis.py.
-- Positive sales and cancellation credits are deliberately reported separately.
SELECT record_type, COUNT(*) AS invoice_lines, ROUND(SUM(line_value), 2) AS recorded_value_gbp
FROM invoice_lines GROUP BY record_type;

SELECT month,
 ROUND(SUM(CASE WHEN record_type = 'sale' THEN line_value ELSE 0 END), 2) AS gross_positive_value_gbp,
 ROUND(-SUM(CASE WHEN record_type = 'cancellation_credit' THEN line_value ELSE 0 END), 2) AS cancellation_credit_value_gbp,
 ROUND(SUM(line_value), 2) AS net_recorded_value_gbp
FROM invoice_lines GROUP BY month ORDER BY month;

SELECT Country, ROUND(SUM(CASE WHEN record_type = 'sale' THEN line_value ELSE 0 END), 2) AS gross_positive_value_gbp
FROM invoice_lines GROUP BY Country ORDER BY gross_positive_value_gbp DESC LIMIT 8;
